FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt /app
COPY docs /app/docs
COPY mkdocs.yml /app

RUN pip install -r requirements.txt

ENV MKDOCS_PORT=8000

EXPOSE ${MKDOCS_PORT}

CMD ["sh", "-c", "mkdocs serve --dev-addr=0.0.0.0:${MKDOCS_PORT}"]
