@baseUrl = http://localhost:8080

@topic_sample_01 = sample.foo-topic.0
@topic_sample_02 = sample.bar-topic.0

### Get Status
GET {{baseUrl}}/status

### Publish Topic Messages
POST {{baseUrl}}/topics/{{topic_sample_01}}/messages

{
	"messages": [
		{
			"foo": "bar"
		},
		{
			"foo": "baz"
		}
	]
}

### Publish Topic Messages
POST {{baseUrl}}/topics/{{topic_sample_02}}/messages

{
	"messages": [
		{
			"foo": "bar"
		},
		{
			"foo": "baz"
		}
	]
}