name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG]: "
labels: bug

body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clearly and concisely describe the bug.
      placeholder: "I was trying to..."
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: "The page should have loaded the user data..."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide the steps required to reproduce the bug.
      placeholder: "1. Go to '...'\n2. Click on '...'\n3. See error"
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other relevant context, such as screenshots, documentation links, or references.
      placeholder: "Screenshots, logs, or links to relevant documentation..."
    validations:
      required: false

  - type: dropdown
    id: can_fix
    attributes:
      label: Can you solve this issue?
      description: Are you able to open a PR to solve this issue? We don't require you to fix it.
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: checkboxes
    id: confirm_checks
    attributes:
      label: Required confirmations
      description: Please check all the boxes below before opening this Issue.
      options:
        - label: I have searched and confirmed this Issue does not already exist
          required: true
        - label: I have read the [CODE_OF_CONDUCT.md](../CODE_OF_CONDUCT.md)
          required: true
        - label: I have read the [CONTRIBUTING.md](../CONTRIBUTING.md)
          required: true