name: 🔧 Chore
description: General maintenance tasks or requests that are not feature, bug, docs, refactor, or CI related
title: "[CHORE]: "
labels: chore

body:
  - type: textarea
    id: chore_description
    attributes:
      label: Chore Description
      description: Clearly describe the task or maintenance request.
      placeholder: "Update dependencies to the latest versions..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain why this chore is necessary or valuable.
      placeholder: "Keeping dependencies up to date improves security and stability..."
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other relevant information, such as links, files, or related issues.
      placeholder: "Related issues, documentation, or screenshots..."
    validations:
      required: false

  - type: dropdown
    id: can_fix
    attributes:
      label: Can you solve this issue?
      description: Are you able to open a PR to solve this issue? We don't require you to fix it.
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: checkboxes
    id: confirm_checks
    attributes:
      label: Required confirmations
      description: Please check all the boxes below before opening this Issue.
      options:
        - label: I have searched and confirmed this Issue does not already exist
          required: true
        - label: I have read the [CODE_OF_CONDUCT.md](../CODE_OF_CONDUCT.md)
          required: true
        - label: I have read the [CONTRIBUTING.md](../CONTRIBUTING.md)
          required: true