name: ⚙️ CI
description: Suggest improvements or report issues related to CI/CD pipelines and automation
title: "[CI]: "
labels: ci

body:
  - type: textarea
    id: ci_issue
    attributes:
      label: CI/CD Issue or Suggestion
      description: Describe the problem or improvement related to the CI/CD pipeline, automation scripts, or workflows.
      placeholder: "The deployment job fails on step X..."
    validations:
      required: true

  - type: textarea
    id: expected_outcome
    attributes:
      label: Expected Outcome
      description: Describe the desired or expected outcome after this issue is addressed.
      placeholder: "The workflow should pass all tests and deploy successfully..."
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any logs, screenshots, or other relevant information.
      placeholder: "Include error messages, workflow run links, or configuration snippets..."
    validations:
      required: false

  - type: dropdown
    id: can_fix
    attributes:
      label: Can you solve this issue?
      description: Are you able to open a PR to solve this issue? We don't require you to fix it.
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: checkboxes
    id: confirm_checks
    attributes:
      label: Required confirmations
      description: Please check all the boxes below before opening this Issue.
      options:
        - label: I have searched and confirmed this Issue does not already exist
          required: true
        - label: I have read the [CODE_OF_CONDUCT.md](../CODE_OF_CONDUCT.md)
          required: true
        - label: I have read the [CONTRIBUTING.md](../CONTRIBUTING.md)
          required: true