name: 📝 Documentation
description: Request for creation, improvement, or addition to the documentation
title: "[DOCS]: "
labels: docs

body:
  - type: textarea
    id: improvement
    attributes:
      label: Description
      description: Clearly describe what needs to be done or improved in the documentation.
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any additional relevant context, such as screenshots, documentation links, or references.
    validations:
      required: false

  - type: dropdown
    id: can_fix
    attributes:
      label: Can you solve this issue?
      description: Are you able to open a PR to solve this issue? We don't require you to fix it.
      options:
        - Yes
        - No
    validations:
      required: true

  - type: checkboxes
    id: confirm_checks
    attributes:
      label: Required confirmations
      description: Please check all the boxes below before opening this Issue.
      options:
        - label: I have searched and confirmed this Issue does not already exist
          required: true
        - label: I have read the [CODE_OF_CONDUCT.md](../CODE_OF_CONDUCT.md)
          required: true
        - label: I have read the [CONTRIBUTING.md](../CONTRIBUTING.md)
          required: true
