name: Build and Publish Docker Image

on:
  release:
    types: [published]
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/publish_docs.yml'
      - '.github/workflows/ci.yml'
      - '.editorconfig'
      - '.gitignore'
      - 'golangci.yml'
      - '*.md'
      - 'docker-compose.yml'
      - 'Dockerfile.mkdocs'
      - 'LICENSE'
      - 'mkdocs.yml'
      - 'README.md'
      - '*.http'
      - 'Makefile'
      - 'requirements.txt'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build_and_publish:
    if: github.event.release.draft == false
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and push image
        if: success()
        run: |
          docker buildx build -t mauricioromagnollo/kafrest:latest --platform linux/amd64,linux/arm64 --push .
